# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequestsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'DailyRequestsStatistics',
                'verbose_name_plural': 'DailyRequestsStatistics',
            },
        ),
    ]
