# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrequestsstatistics',
            old_name='json',
            new_name='json_data',
        ),
    ]
