# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20160110_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='uid')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('json_description', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ABTest',
                'verbose_name_plural': 'ABTests',
            },
        ),
        migrations.CreateModel(
            name='DailyABStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Data')),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ab_statistics', to='analytics.ABTest', verbose_name='AB test')),
            ],
            options={
                'verbose_name': 'DailyABStatistics',
                'verbose_name_plural': 'DailyABStatistics',
            },
        ),
    ]
